import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";

export default defineConfig({
  base: process.env.VITE_BASE || "/",
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  optimizeDeps: {
    include: [
      "react",
      "react-dom",
      "clsx",
      "three",
      "@react-three/fiber",
      "@react-three/drei",
      "framer-motion",
      "gsap",
      "gsap/all",
      "@gsap/react",
      "gsap/ScrollTrigger",
      "gsap/ScrollToPlugin",
      "gsap/Draggable",
      "gsap/MotionPathPlugin",
      "gsap/TextPlugin",
      "gsap/Flip",
      "gsap/Observer",
      "gsap/EasePack",
      "gsap/CustomEase",
      "gsap/SplitText",
      "react-icons/fi",
      "react-icons/fa",
      "react-icons/fa6",
      "react-icons/md",
      "react-icons/io",
      "react-icons/io5",
      "react-icons/ai",
      "react-icons/bi",
      "react-icons/bs",
      "react-icons/ci",
      "react-icons/cg",
      "react-icons/di",
      "react-icons/gi",
      "react-icons/go",
      "react-icons/gr",
      "react-icons/hi",
      "react-icons/hi2",
      "react-icons/im",
      "react-icons/lu",
      "react-icons/pi",
      "react-icons/ri",
      "react-icons/rx",
      "react-icons/si",
      "react-icons/sl",
      "react-icons/tb",
      "react-icons/tfi",
      "react-icons/ti",
      "react-icons/vsc",
      "react-icons/wi",
      "tailwind-merge",
    ],
  },
  server: {
    host: "0.0.0.0",
    port: 3000,
    strictPort: true,
    hmr: {
      overlay: false,
      clientPort: 443,
      path: `/${process.env.VITE_BASE?.replace(/^\/|\/$/g, "") || ""}/`,
    },
    allowedHosts: true,
  },
});
